### ISSUE TITLE
start:server getting "SyntaxError: Unexpected token import" with some 3rd party libraries

### ISSUE THREAD

**Issue by cj-wang** [kamilmysliwiec/universal-nest#12]
Thanks for the great example!
I'm having a small issue here, the dev server stops working with some 3rd part libraries, e.g. Nebular.
Issue can be reproduced here: https://github.com/cj-wang/universal-nest/tree/nebular
```
import { InjectionToken } from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.@nebular/theme/theme.options 
```

**Comment by alex-osman** [comment]
Having this problem with many 3rd party libraries as well

**Comment by kamilmysliwiec** [comment]
This issue is not related to Nest itself. I'd suggest looking here https://github.com/angular/angular-cli/issues/7200
