### ISSUE TITLE
serve:ssr will fail if integrated with mongodb/mongoose

### ISSUE THREAD

**Issue by wunaidage** [kamilmysliwiec/universal-nest#16]
I try to add a mongodb module in the server side, then run serve:ssr after fresh build:ssr. the server will fail and error is 
`Error: Cannot find module './drivers/node-mongodb-native/connection'`
is webpack not working with mongoose?

**Comment by wunaidage** [comment]
fixed the issue: 
the default WebpackConfigFactory settings in webpack.server.config.js is not well set up for such scenario.
I changed to the following and add more things in output and externals.
```javascript
const path = require('path');
const webpack = require('webpack');

module.exports = {
  mode: 'none',
  entry: {
    server: './server/main.ts',
  },
  target: 'node',
  resolve: { extensions: ['.ts', '.js'] },
  optimization: {
    minimize: false,
  },
  output: {
    // Puts the output at the root of the dist folder
    path: path.join(__dirname, 'dist'),
    filename: '[name].js',
    libraryTarget: 'commonjs'
  },
  // this makes sure we include node_modules and other 3rd party libraries
  externals: [/^(?!\.|\/).+/i],
  module: {
    rules: [{ test: /\.ts$/, loader: 'ts-loader' }]
  },
  plugins: [
    new webpack.ContextReplacementPlugin(/((.+)?angular(\\|\/)core(.+)?|express(.+)?|(.+)?nestjs(\\|\/)(.+)?)?/, path.join(process.cwd(), 'src'), {})
  ],
};

```

**Comment by kamilmysliwiec** [comment]
Interesting. Thanks for sharing your solution.

**Comment by chriszrc** [comment]
I'm having a similar problem, I added typeorm, and can't seem to figure out how to properly setup the references to my entities ("Mortality" is the first entity), I keep getting:

```
/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:267827
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "Mortality", function() { return Mortality; });
                                                                                                    ^

ReferenceError: Mortality is not defined
    at Module.Mortality (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:267827:101)
    at Module.<anonymous> (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:268092:115)
    at __webpack_require__ (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:20:30)
    at Module.<anonymous> (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:267831:85)
    at __webpack_require__ (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:20:30)
    at Module.Object.defineProperty.value (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:253988:75)
    at __webpack_require__ (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:20:30)
    at Module.<anonymous> (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:253951:76)
    at __webpack_require__ (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:20:30)
    at Module.exports.__esModule (/Users/chris/github/proj-who-anacod/web/anacod-app-universal/dist/server.js:59922:85)
```

Thoughts?

**Comment by chriszrc** [comment]
I'm having a similar problem, I added typeorm, and can't seem to figure out how to properly setup the references to my entities ("Mortality" is the first entity), I keep getting:

```
/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:267827
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "Mortality", function() { return Mortality; });
                                                                                                    ^

ReferenceError: Mortality is not defined
    at Module.Mortality (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:267827:101)
    at Module.<anonymous> (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:268092:115)
    at __webpack_require__ (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:20:30)
    at Module.<anonymous> (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:267831:85)
    at __webpack_require__ (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:20:30)
    at Module.Object.defineProperty.value (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:253988:75)
    at __webpack_require__ (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:20:30)
    at Module.<anonymous> (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:253951:76)
    at __webpack_require__ (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:20:30)
    at Module.exports.__esModule (/Users/chris/github/proj-who-test/web/test-app-universal/dist/server.js:59922:85)
```

The app runs fine locally, just not with SSR-
Thoughts?

**Comment by Jeerjmin** [comment]
I'm having a similar problem

 Cannot find module './drivers/node-mongodb-native/connection'

And @wunaidage solution to forward to another problem.

[Nest] 10520   - 2019-06-06 17:21   [ExceptionsHandler] Cannot read property 'moduleType' of undefined +2701ms
TypeError: Cannot read property 'moduleType' of undefined


I fixed this by changing webpack.server.config.js
```
module.exports = WebpackConfigFactory.create(webpack, {
    // This is our Nest server for Dynamic universal
    server: './server/main.ts',
    prerender: './prerender.ts',
}, __dirname, process.cwd() );
```

And node_modules\@nestjs\ng-universal\dist\webpack-config.factory.js

```

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const path_1 = require("path");
const nodeExternals = require("webpack-node-externals");
const defaultEntries = {
    server: './server/main.ts'
};
class WebpackConfigFactory {
    static create(webpack, entry = defaultEntries, currentDir = process.cwd(), projectDir = currentDir) {
        return {
            entry,
            mode: 'none',
            target: 'node',
            optimization: {
                minimize: false,
            },
            resolve: { extensions: ['.ts', '.js'] },
            externals: [/^(?!\.|\/).+/i],
            output: {
                path: path_1.join(currentDir, 'dist'),
                filename: '[name].js',
                libraryTarget: 'commonjs'
            },
            module: {
                rules: [
                    { test: /\.ts$/, loader: 'ts-loader' },
                    {
                        test: /(\\|\/)@angular(\\|\/)core(\\|\/).+\.js$/,
                        parser: { system: true }
                    },
                    {
                        test: /\module.ts$/,
                        loader: 'string-replace-loader',
                        options: {
                            search: '../server/main',
                            replace: '../dist/server/main',
                            flags: 'g'
                        }
                    }
                ]
            },
            plugins: [
                new webpack.ContextReplacementPlugin(/((.+)?angular(\\|\/)core(.+)?|express(.+)?|(.+)?nestjs(\\|\/)(.+)?)?/, path_1.join(projectDir, 'src'), {})
            ]
        };
    }
}
exports.WebpackConfigFactory = WebpackConfigFactory;

```

**Comment by chriszrc** [comment]
> I'm having a similar problem, I added typeorm, and can't seem to figure out how to properly setup the references to my entities ("Mortality" is the first entity), I keep getting:

So, after digging into this more, there are all kinds of problems you can run into when using webpack, if you're expecting to be able to reference files outside your bundle.

For database drivers like sqlite (and I assume mongo, etc), they need to be declared as externals in the webpack config, and the libs need to be available in node_module where the app is being built. 

For my typeorm problem, the default configuration for typeorm using a directory path to scan for entities. Obviously that won't work either, you either have to defined the entities by direct reference, or figure out how to compile them and make them available separately within your dist folder. 

```
TypeOrmModule.forRoot({
      type: 'sqlite',
      synchronize: true,
      logging: true,
      logger: 'simple-console',
      database: __dirname + '/database.sqlite',
      //__dirname + '/**/*.entity{.ts,.js}' //NOT THIS
      entities: [Item],
    }),
```

**Comment by nomankt** [comment]
+1
