### ISSUE TITLE
error in npm run generate:prerender

### ISSUE THREAD

**Issue by nourissam** [kamilmysliwiec/universal-nest#28]
Hello
when i run **npm run generate:prerender**  i have this error :
ERROR { Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (C:\Users\issam\Desktop\nest-nguniversal-demo\dist\prerender.js:145231:30)
    at Function.requireEnsure [as e] (C:\Users\issam\Desktop\nest-nguniversal-demo\dist\prerender.js:145250:25)
    at ɵ0 (C:\Users\issam\Desktop\nest-nguniversal-demo\dist\prerender.js:145445:38)

someone help me plz

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by flippii** [comment]
Hello,

same Issue on:
- Windows 10
- Node 10.17.0
- NPM 6.12.0

I check out the code and run build:prerender.

Then i have an Error in generate:prerender step:

`ERROR { Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (c:\some_folder\dist\prerender.js:145231:30)
    at Function.requireEnsure [as e] (c:\some_folder\dist\prerender.js:145250:25)
    at ɵ0 (c:\some_folder\dist\prerender.js:145445:38)
    at RouterConfigLoader.loadModuleFactory (c:\some_folder\dist\prerender.js:149622:39)
    at RouterConfigLoader.load (c:\some_folder\dist\prerender.js:149607:35)
    at MergeMapSubscriber.project (c:\some_folder\dist\prerender.js:148610:47)
    at MergeMapSubscriber._tryNext (c:\some_folder\dist\prerender.js:88799:27)
    at MergeMapSubscriber._next (c:\some_folder\dist\prerender.js:88789:18)
    at MergeMapSubscriber.Subscriber.next (c:\some_folder\dist\prerender.js:85348:18)
    at Observable._subscribe (c:\some_folder\dist\prerender.js:87360:24)
    at resolvePromise (c:\some_folder\dist\prerender.js:2436:31)
    at resolvePromise (c:\some_folder\dist\prerender.js:2393:17)
    at c:\some_folder\dist\prerender.js:2497:17
    at ZoneDelegate.invokeTask (c:\some_folder\dist\prerender.js:2007:31)
    at Object.onInvokeTask (c:\some_folder\dist\prerender.js:80535:33)
    at ZoneDelegate.invokeTask (c:\some_folder\dist\prerender.js:2006:60)
    at Zone.runTask (c:\some_folder\dist\prerender.js:1779:47)
    at drainMicroTaskQueue (c:\some_folder\dist\prerender.js:2185:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
  rejection:
   TypeError: Cannot read property 'call' of undefined
       at __webpack_require__ (c:\some_folder\dist\prerender.js:145231:30)
       at Function.requireEnsure [as e] (c:\some_folder\dist\prerender.js:145250:25)
       at ɵ0 (c:\some_folder\dist\prerender.js:145445:38)
       at RouterConfigLoader.loadModuleFactory (c:\some_folder\dist\prerender.js:149622:39)
       at RouterConfigLoader.load (c:\some_folder\dist\prerender.js:149607:35)
       at MergeMapSubscriber.project (c:\some_folder\dist\prerender.js:148610:47)
       at MergeMapSubscriber._tryNext (c:\some_folder\dist\prerender.js:88799:27)
       at MergeMapSubscriber._next (c:\some_folder\dist\prerender.js:88789:18)
       at MergeMapSubscriber.Subscriber.next (c:\some_folder\dist\prerender.js:85348:18)
       at Observable._subscribe (c:\some_folder\dist\prerender.js:87360:24),
  promise:
   ZoneAwarePromise [Promise] {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      TypeError: Cannot read property 'call' of undefined
          at __webpack_require__ (c:\some_folder\dist\prerender.js:145231:30)
          at Function.requireEnsure [as e] (c:\some_folder\dist\prerender.js:145250:25)
          at ɵ0 (c:\some_folder\dist\prerender.js:145445:38)
          at RouterConfigLoader.loadModuleFactory (c:\some_folder\dist\prerender.js:149622:39)
          at RouterConfigLoader.load (c:\some_folder\dist\prerender.js:149607:35)
          at MergeMapSubscriber.project (c:\some_folder\dist\prerender.js:148610:47)
          at MergeMapSubscriber._tryNext (c:\some_folder\dist\prerender.js:88799:27)
          at MergeMapSubscriber._next (c:\some_folder\dist\prerender.js:88789:18)
          at MergeMapSubscriber.Subscriber.next (c:\some_folder\dist\prerender.js:85348:18)
          at Observable._subscribe (c:\some_folder\dist\prerender.js:87360:24) },
  zone:
   Zone {
     _parent:
      Zone {
        _parent: null,
        _name: '<root>',
        _properties: {},
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _properties: { isAngularZone: true },
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _parent: [Zone],
        _name: 'angular',
        _properties: [Object],
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise [Promise] {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         TypeError: Cannot read property 'call' of undefined
             at __webpack_require__ (c:\some_folder\dist\prerender.js:145231:30)
             at Function.requireEnsure [as e] (c:\some_folder\dist\prerender.js:145250:25)
             at ɵ0 (c:\some_folder\dist\prerender.js:145445:38)
             at RouterConfigLoader.loadModuleFactory (c:\some_folder\dist\prerender.js:149622:39)
             at RouterConfigLoader.load (c:\some_folder\dist\prerender.js:149607:35)
             at MergeMapSubscriber.project (c:\some_folder\dist\prerender.js:148610:47)
             at MergeMapSubscriber._tryNext (c:\some_folder\dist\prerender.js:88799:27)
             at MergeMapSubscriber._next (c:\some_folder\dist\prerender.js:88789:18)
             at MergeMapSubscriber.Subscriber.next (c:\some_folder\dist\prerender.js:85348:18)
             at Observable._subscribe (c:\some_folder\dist\prerender.js:87360:24) },
     scheduleFn: undefined,
     cancelFn: undefined,
     callback: [Function],
     invoke: [Function] } }
`

Can someone help please.

**Comment by cfremgen** [comment]
@kamilmysliwiec 

The minimal repository is this one. Pre-rendering does not work.

**Comment by kamilmysliwiec** [comment]
Prerendering is now shipped by Angular team as part of the official Universal package.  Simply run `npm run prerender` to prerender your application. If you face any issue, please, report this in the official repository https://github.com/angular/universal
