### ISSUE TITLE
use prerenderer

### ISSUE THREAD

**Issue by DrMabuse23** [kamilmysliwiec/universal-nest#3]
Hey Thx for this nice example, but i git an error on prerenderer.
the comand i use
````
npm run build:prerender && npm run serve:prerender
````
The error
````
Users/pascalbrewing/htdocs/universal-nest/dist/prerender.js:112618
'function' === typeof document.createEvent ? function CustomEvent (type, params) {
                      ^

ReferenceError: document is not defined
    at Object.eventmap (/htdocs/universal-nest/dist/prerender.js:112618:23)
    at __webpack_require__ (/htdocs/universal-nest/dist/prerender.js:20:30)
    at Object.NativeCustomEvent (/htdocs/universal-nest/dist/prerender.js:112490:19)
    at __webpack_require__ (/htdocs/universal-nest/dist/prerender.js:20:30)
    at Object.<anonymous> (/htdocs/universal-nest/dist/prerender.js:111775:17)
    at __webpack_require__ (//htdocs/universal-nest/dist/prerender.js:20:30)
    at Module.<anonymous> (/htdocs/universal-nest/dist/prerender.js:111017:65)
    at __webpack_require__ (/htdocs/universal-nest/dist/prerender.js:20:30)
    at Object.ng2-dragula (/htdocs/universal-nest/dist/prerender.js:105256:18)
    at __webpack_require__ (/htdocs/universal-nest/dist/prerender.js:104518:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-nguniversal-demo@0.1.0 generate:prerender: `cd dist && node prerender`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nest-nguniversal-demo@0.1.0 generate:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging
````

i didnt change anything in the code.

infos : 
````
node -v            v8.11.3
npm -v              6.4.1
````

**Comment by DrMabuse23** [comment]
ok what i can see is a change in package-lock.josn 
before : 
````
 "@nestjs/ng-universal": {
      "version": "0.0.1",
      "resolved": "https://registry.npmjs.org/@nestjs/ng-universal/-/ng-universal-0.0.1.tgz",
      "integrity": "sha512-/2igQ7+SpfY2GfjxIbU54M4N5UtMCcs71JyBMr2A72mi8MPBYRrXBz/X1iuKQKU1MX3mjA1KsPJU9z6b7BgRZA=="
````
after
````
# "version": "0.1.0",
      "resolved": "https://registry.npmjs.org/@nestjs/ng-universal/-/ng-universal-0.1.0.tgz",
      "integrity": "sha512-WGg5+im39/++y/4NkKj3OIeMDqK//4AQ9HBh5xGmocqCKXRNSuY2AujXw5aU4k4RPh9ewhNLcuC/STqhFvy/ww=="
````

**Comment by kamilmysliwiec** [comment]
Very weird. I just pulled the repo again and everything works correctly for me.

**Comment by sxlwar** [comment]
@DrMabuse23 have you solved ?

**Comment by DrMabuse23** [comment]
@sxlwar yes same on me i pulled again everything works

**Comment by 6matko** [comment]
Sorry to bump this issue again, but I have the same issue. Pulled repo twice and both times I get this issue.
Only difference is that I have node v9.9.0.

Also tried removing package-lock.json and install again, installing prerender globally and both didn't work. AFAIK, it fails here: `cd dist && node prerender`. Maybe I am missing something? :/

**Comment by hiepxanh** [comment]
i dont know something wrong with me but I have the same problem
