### ISSUE TITLE
[Bug] Prerendering build error

### ISSUE THREAD

**Issue by KingDarBoja** [kamilmysliwiec/universal-nest#34]
This is the same issue as #28.

Clonned the project, ran `npm install --verbose` and then tested the ssr script, which works fine. However, the prerendering one throws an error on the build step (`npm run build:prerender`):

```console
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (D:\Programming\ts_projects\universal-nest\dist\prerender.js:145231:30)
    at Function.requireEnsure [as e] (D:\Programming\ts_projects\universal-nest\dist\prerender.js:145250:25)
    at ɵ0 (D:\Programming\ts_projects\universal-nest\dist\prerender.js:145445:38)
    at RouterConfigLoader.loadModuleFactory (D:\Programming\ts_projects\universal-nest\dist\prerender.js:149622:39)
    at RouterConfigLoader.load (D:\Programming\ts_projects\universal-nest\dist\prerender.js:149607:35)
    at MergeMapSubscriber.project (D:\Programming\ts_projects\universal-nest\dist\prerender.js:148610:47)
    at MergeMapSubscriber._tryNext (D:\Programming\ts_projects\universal-nest\dist\prerender.js:88799:27)
    at MergeMapSubscriber._next (D:\Programming\ts_projects\universal-nest\dist\prerender.js:88789:18)
    at MergeMapSubscriber.Subscriber.next (D:\Programming\ts_projects\universal-nest\dist\prerender.js:85348:18)
    at Observable._subscribe (D:\Programming\ts_projects\universal-nest\dist\prerender.js:87360:24)
```

It is way longer so I am not pasting the entire log error.
Also, the prerendering stop working when navigating to the provided urls, nothing is loaded.

The issue seems to be related to route lazy loading. If I find a solution, I will make a PR for this repo.

**EXTRA INFORMATION**
- **ANGULAR**
```console
Your global Angular CLI version (8.3.21) is greater than your local
version (8.1.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.1.1
Node: 12.14.0
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.1
@angular-devkit/build-angular              0.801.1
@angular-devkit/build-optimizer            0.801.1
@angular-devkit/build-webpack              0.801.1
@angular-devkit/core                       8.1.1
@angular-devkit/schematics                 8.1.1
@ngtools/webpack                           8.1.1
@nguniversal/common                        8.1.1
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.1.1
@schematics/update                         0.801.1
rxjs                                       6.5.2
typescript                                 3.4.4
webpack                                    4.35.2
```

- **NESTJS**
```console
 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : Windows 10
NodeJS Version : v12.14.0
NPM Version    : 6.13.4
[Nest Information]
platform-express version : 6.5.2
ng-universal version     : 2.0.0
common version           : 6.5.2
core version             : 6.5.2
```

Cheers!

**UPDATE** Updated all dependencies (by using `ncu`) to latest version and the error still shows up but the prerendering is working now.

![image](https://user-images.githubusercontent.com/30560560/71784362-d90dad80-2fc0-11ea-8e1b-dd7ab89ef28a.png)

**Comment by KingDarBoja** [comment]
Found the issue after checking the related [migration guide](https://github.com/angular/universal/blob/master/docs/v8-upgrade-guide.md) at Angular/Universal repo and checking similar issues at that repo: Angular/Universal#1169 and Angular/Universal#31092.

Change the module option at **tsconfig.json** file to `commonjs` (was `esnext`).

After that, the error is gone and the `npm run build:prerender` step throws the following message:
```console
intercepting the url /api/speakers
ERROR [NetworkError]
```

**Comment by kamilmysliwiec** [comment]
Prerendering is now shipped by Angular team as part of the official Universal package.  Simply run `npm run prerender` to prerender your application. If you face any issue, please, report this in the official repository https://github.com/angular/universal
