### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by eugenotop** [kamilmysliwiec/universal-nest#6]
yarn build:ssr
yarn run v1.12.3
$ npm run build:client-and-server-bundles && npm run webpack:server
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1544481679844-0.6985739033224607/node but npm is using .nvm/versions/node/v8.12.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> nest-nguniversal-demo@0.1.0 build:client-and-server-bundles /universal-nest-master
> ng build --prod && ng run nest-nguniversal-demo:server:production

Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

ValidationError: Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

    at validateOptions (/universal-nest-master/node_modules/schema-utils/src/validateOptions.js:31:11)
    at new ProgressPlugin (/universal-nest-master/node_modules/webpack/lib/ProgressPlugin.js:90:3)
    at Object.getCommonConfig (/universal-nest-master/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js:123:27)
    at BrowserBuilder.buildWebpackConfig (/universal-nest-master/node_modules/@angular-devkit/build-angular/src/browser/index.js:74:31)
    at MergeMapSubscriber.rxjs_1.of.pipe.operators_1.concatMap [as project] (/universal-nest-master/node_modules/@angular-devkit/build-angular/src/browser/index.js:31:38)
    at MergeMapSubscriber._tryNext (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at TapSubscriber._next (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/tap.js:62:26)
    at TapSubscriber.Subscriber.next (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/observable/forkJoin.js:79:25)
    at InnerSubscriber._complete (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:32:21)
    at InnerSubscriber.Subscriber.complete (/universal-nest-master/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:76:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-nguniversal-demo@0.1.0 build:client-and-server-bundles: `ng build --prod && ng run nest-nguniversal-demo:server:production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nest-nguniversal-demo@0.1.0 build:client-and-server-bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    /.npm/_logs/2018-12-10T22_41_22_649Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mohammedzamakhan** [comment]
Same here

**Comment by mohammedzamakhan** [comment]
any updates @kamilmysliwiec

**Comment by kamilmysliwiec** [comment]
It doesn't seem to be an issue with this repo particularly but rather something wrong with your current, local configuration/environment. I'd suggest removing `node_modules`, `package-lock` (or `yarn.lock` in this case), updating all dependencies, and reinstalling them all.
